# Generated by Django 5.2.12 on 2026-03-13 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BonCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=50, unique=True)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('ENVOYE', 'Envoyé au fournisseur'), ('RECU', 'Reçu partiellement'), ('RECU_TOTAL', 'Reçu en totalité'), ('ANNULE', 'Annulé')], default='BROUILLON', max_length=15)),
                ('fournisseur_nom', models.CharField(max_length=200)),
                ('fournisseur_contact', models.CharField(blank=True, max_length=100)),
                ('fournisseur_tel', models.CharField(blank=True, max_length=20)),
                ('fournisseur_email', models.EmailField(blank=True, max_length=254)),
                ('fournisseur_adresse', models.TextField(blank=True)),
                ('date_commande', models.DateField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_livraison_prev', models.DateField(blank=True, null=True)),
                ('total_ht', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('retenue_5pct', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('bic_2pct', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_net', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdfs/commandes/')),
                ('notes', models.TextField(blank=True)),
                ('objet', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'Bon de Commande',
                'verbose_name_plural': 'Bons de Commande',
                'ordering': ['-date_commande'],
            },
        ),
        migrations.CreateModel(
            name='LigneBonCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('prix_unitaire_ht', models.DecimalField(decimal_places=2, max_digits=14)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_ht', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('unite', models.CharField(blank=True, max_length=50)),
                ('ordre', models.IntegerField(default=0)),
                ('bon_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='commandes.boncommande')),
            ],
            options={
                'verbose_name': 'Ligne de Bon de Commande',
                'verbose_name_plural': 'Lignes de Bon de Commande',
                'ordering': ['ordre'],
            },
        ),
    ]
