# Generated by Django 5.2.12 on 2026-03-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ligneboncommande',
            old_name='reference',
            new_name='delais',
        ),
        migrations.AddField(
            model_name='boncommande',
            name='date_proforma_fournisseur',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boncommande',
            name='delais_livraison',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='boncommande',
            name='fournisseur_division_fiscale',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='boncommande',
            name='fournisseur_ifu',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='boncommande',
            name='fournisseur_rccm',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='boncommande',
            name='fournisseur_regime',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='boncommande',
            name='ref_proforma_fournisseur',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='boncommande',
            name='termes_livraison',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='boncommande',
            name='termes_paiement',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='boncommande',
            name='tva_18pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='ligneboncommande',
            name='reference_client',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ligneboncommande',
            name='reference_fournisseur',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
