# Generated by Django 5.2.12 on 2026-03-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0002_rename_reference_ligneboncommande_delais_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boncommande',
            name='appliquer_bic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boncommande',
            name='appliquer_retenue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boncommande',
            name='appliquer_tva',
            field=models.BooleanField(default=False),
        ),
    ]
