# Generated by Django 5.2.12 on 2026-03-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0003_boncommande_appliquer_bic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boncommande',
            name='appliquer_remise',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boncommande',
            name='appliquer_transport',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boncommande',
            name='montant_remise',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='boncommande',
            name='montant_transport',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='boncommande',
            name='remise_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='boncommande',
            name='total_ht_brut',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
