# Generated by Django 5.2.12 on 2026-03-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0004_boncommande_appliquer_remise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boncommande',
            name='validite_jours',
            field=models.IntegerField(default=30),
        ),
    ]
