# Generated by Django 5.2.12 on 2026-03-31 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0005_boncommande_validite_jours'),
    ]

    operations = [
        migrations.AddField(
            model_name='boncommande',
            name='date_deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boncommande',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='boncommande',
            name='date_commande',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
