# Generated by Django 5.2.12 on 2026-04-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0006_boncommande_date_deleted_boncommande_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boncommande',
            name='date_deleted',
        ),
        migrations.RemoveField(
            model_name='boncommande',
            name='is_deleted',
        ),
        migrations.AlterField(
            model_name='boncommande',
            name='date_commande',
            field=models.DateField(auto_now_add=True),
        ),
    ]
