# Generated by Django 5.2.12 on 2026-04-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0007_remove_boncommande_date_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boncommande',
            name='date_deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boncommande',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
