# Generated by Django 5.2.12 on 2026-03-31 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OffreService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('langue', models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', max_length=2)),
                ('societe', models.CharField(blank=True, max_length=200)),
                ('destinataires', models.JSONField(blank=True, default=list)),
                ('texte_custom', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Offre de service',
                'verbose_name_plural': 'Offres de service',
                'ordering': ['-date_creation'],
            },
        ),
    ]
