# Generated by Django 5.2.12 on 2026-04-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offreservice',
            name='date_suppression',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offreservice',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
