# Generated by Django 5.2.12 on 2026-04-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offres', '0002_offreservice_date_suppression_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offreservice',
            name='adresse',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='offreservice',
            name='date_doc',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
