# Generated by Django 5.2.12 on 2026-03-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(max_length=200)),
                ('contact_nom', models.CharField(blank=True, max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.TextField(blank=True)),
                ('rccm', models.CharField(blank=True, max_length=100)),
                ('ifu', models.CharField(blank=True, max_length=50)),
                ('regime_imposition', models.CharField(blank=True, choices=[('RNI', "Régime Normal d'Imposition"), ('RSI', "Régime Simplifié d'Imposition"), ('AI', 'Auto-Entrepreneur')], max_length=10)),
                ('division_fiscale', models.CharField(blank=True, max_length=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['nom_entreprise'],
            },
        ),
    ]
