# Generated by Django 5.2.12 on 2026-03-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(max_length=200)),
                ('nom_contact', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('pays', models.CharField(default='Burkina Faso', max_length=100)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('type_application', models.CharField(choices=[('GESTION', 'Application de gestion'), ('ECOMMERCE', 'Site e-commerce'), ('VITRINE', 'Site vitrine'), ('MOBILE', 'Application mobile'), ('ERP', 'ERP / CRM'), ('AUTRE', 'Autre')], default='GESTION', max_length=20)),
                ('budget', models.CharField(choices=[('MOINS_500K', 'Moins de 500 000 FCFA'), ('500K_1M', '500 000 — 1 000 000 FCFA'), ('1M_3M', '1 000 000 — 3 000 000 FCFA'), ('PLUS_3M', 'Plus de 3 000 000 FCFA'), ('A_DISCUTER', 'À discuter')], default='A_DISCUTER', max_length=20)),
                ('description', models.TextField()),
                ('fonctionnalites', models.TextField(blank=True)),
                ('delai_souhaite', models.CharField(blank=True, max_length=100)),
                ('statut', models.CharField(choices=[('NOUVEAU', 'Nouveau'), ('EN_COURS', 'En cours de traitement'), ('CONTACTE', 'Client contacté'), ('DEVIS_ENVOYE', 'Devis envoyé'), ('ACCEPTE', 'Accepté'), ('REFUSE', 'Refusé')], default='NOUVEAU', max_length=20)),
                ('notes_internes', models.TextField(blank=True)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Demande Application',
                'verbose_name_plural': 'Demandes Applications',
                'ordering': ['-date_demande'],
            },
        ),
    ]
