# Generated by Django 5.2.12 on 2026-03-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_demandeapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeapplication',
            name='type_application',
            field=models.CharField(choices=[('GESTION', 'Application de gestion'), ('ECOMMERCE', 'Site e-commerce'), ('VITRINE', 'Site vitrine'), ('MOBILE', 'Application mobile'), ('ERP', 'ERP / CRM'), ('AFFICHE', 'Affiche & Flyer'), ('LOGO', 'Logo & Identité visuelle'), ('PACK', 'Pack Digital Complet'), ('AUTRE', 'Autre')], default='GESTION', max_length=20),
        ),
    ]
