# Generated by Django 5.2.12 on 2026-03-13 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=50, unique=True)),
                ('type_doc', models.CharField(choices=[('PROFORMA', 'Facture Proforma'), ('FACTURE', 'Facture Définitive')], default='PROFORMA', max_length=10)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('ENVOYE', 'Envoyé'), ('VALIDE', 'Validé'), ('PAYE', 'Payé'), ('ANNULE', 'Annulé')], default='BROUILLON', max_length=10)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('validite_jours', models.IntegerField(default=30)),
                ('total_ht', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('retenue_5pct', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('bic_2pct', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_net', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdfs/factures/')),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='clients.client')),
                ('proforma_origine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_generees', to='facturation.facture')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('reference_client', models.CharField(blank=True, max_length=100)),
                ('reference_fournisseur', models.CharField(blank=True, max_length=100)),
                ('prix_unitaire_ht', models.DecimalField(decimal_places=2, max_digits=14)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_ht', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('delais', models.CharField(blank=True, max_length=100)),
                ('ordre', models.IntegerField(default=0)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='facturation.facture')),
            ],
            options={
                'verbose_name': 'Ligne de Facture',
                'verbose_name_plural': 'Lignes de Facture',
                'ordering': ['ordre'],
            },
        ),
    ]
