# Generated by Django 5.2.12 on 2026-03-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='montant_remise',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='facture',
            name='remise_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='facture',
            name='total_ht_brut',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='facture',
            name='tva_18pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
