# Generated by Django 5.2.12 on 2026-03-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0002_facture_montant_remise_facture_remise_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='appliquer_bic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='facture',
            name='appliquer_remise',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='facture',
            name='appliquer_retenue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='facture',
            name='appliquer_tva',
            field=models.BooleanField(default=False),
        ),
    ]
