# Generated by Django 5.2.12 on 2026-03-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0003_facture_appliquer_bic_facture_appliquer_remise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='appliquer_transport',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='facture',
            name='montant_transport',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
