# Generated by Django 5.2.12 on 2026-03-31 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0005_facture_termes_paiement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='termes_paiement',
            field=models.CharField(blank=True, choices=[('100% à la commande', '100% à la commande'), ('15 jours date de facturation', '15 jours date de facturation'), ('30 jours date de facturation', '30 jours date de facturation'), ('60 jours date de facturation', '60 jours date de facturation')], default='', max_length=50),
        ),
    ]
